// var redContent = [
// "<h1>JAM_1</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// "<h1>JAM_2</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// "<h1>JAM_3</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// "<h1>JAM_4</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// ];
// var greenContent = [
// "<h1>RAK_1</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// "<h1>RAK_2</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// "<h1>RAK_3</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// "<h1>RAK_4</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
// ];


var redContent = [
{words: "<h1>JAM_1</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
image: "assets/imgs/jam_1.jpg"},
{words: "<h1>JAM_2</h1><p>Get video posted to internet for chasing red dot sleep on keyboard stare at ceiling light stand with legs in litter box, but poop outside meoooow cat slap dog in face. I could pee on this if i had the energy chase the pig around the house yet howl on top of tall thing for stare at ceiling disappear for four days and return home with an expensive injury; bite the vet lick butt show belly.</p>",
image: "assets/imgs/jam_2.jpg"},
{words: "<h1>JAM_3</h1><p>Sustainable bespoke shoreditch activated charcoal gastropub iceland keytar put a bird on it VHS. Fingerstache wayfarers four loko chia synth. Tousled neutra you probably haven't heard of them, truffaut raw denim cliche semiotics distillery marfa venmo vexillologist. Jean shorts unicorn squid poke coloring book gluten-free taiyaki VHS sustainable.</p>",
image: "assets/imgs/jam_3.jpg"},
{words: "<h1>JAM_4</h1><p>Bacon ipsum dolor amet short loin corned beef tenderloin kevin. Jowl turkey hamburger ground round cow tail. Leberkas jowl ball tip bacon pastrami landjaeger biltong, spare ribs ribeye boudin frankfurter filet mignon picanha. Filet mignon picanha t-bone ground round ball tip strip steak tail andouille spare ribs fatback biltong flank swine capicola doner. Salami ground round shankle pork cupim, chicken tongue tail shoulder jowl meatloaf pork belly ribeye drumstick ball tip.</p>",
image: "assets/imgs/jam_4.jpg"},
];
var greenContent = [
{words: "<h1>RAK_1</h1><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
image: "assets/imgs/rak_1.jpg"},
{words: "<h1>RAK_2</h1><p>Get video posted to internet for chasing red dot sleep on keyboard stare at ceiling light stand with legs in litter box, but poop outside meoooow cat slap dog in face. I could pee on this if i had the energy chase the pig around the house yet howl on top of tall thing for stare at ceiling disappear for four days and return home with an expensive injury; bite the vet lick butt show belly.</p>",
image: "assets/imgs/rak_2.jpg"},
{words: "<h1>RAK_3</h1><p>Sustainable bespoke shoreditch activated charcoal gastropub iceland keytar put a bird on it VHS. Fingerstache wayfarers four loko chia synth. Tousled neutra you probably haven't heard of them, truffaut raw denim cliche semiotics distillery marfa venmo vexillologist. Jean shorts unicorn squid poke coloring book gluten-free taiyaki VHS sustainable.</p>",
image: "assets/imgs/rak_3.jpg"},
{words: "<h1>RAK_4</h1><p>Bacon ipsum dolor amet short loin corned beef tenderloin kevin. Jowl turkey hamburger ground round cow tail. Leberkas jowl ball tip bacon pastrami landjaeger biltong, spare ribs ribeye boudin frankfurter filet mignon picanha. Filet mignon picanha t-bone ground round ball tip strip steak tail andouille spare ribs fatback biltong flank swine capicola doner. Salami ground round shankle pork cupim, chicken tongue tail shoulder jowl meatloaf pork belly ribeye drumstick ball tip.</p>",
image: "assets/imgs/rak_4.jpg"},
];

